config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :memberships, only: [:index, :new, :create, :destroy]
  resources :places, only: [:index, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'toggle_activity', on: :member
  end
  resources :memberships do
    post 'accept', on: :member
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'breweries#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  post 'places', to: 'places#search'

  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'

  #get 'kaikki_bisset', to: 'beers#index'
  #get 'ratings', to: 'ratings#index'
  #get 'ratings/new', to:'ratings#new'
  #post 'ratings', to: 'ratings#create'

end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships
  has_many :members, -> { where("memberships.confirmed = ?", true) }, through: :memberships, source: :user
  has_many :applicants, -> { where("memberships.confirmed = ?", false) }, through: :memberships, source: :user
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: %i[show edit update destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :check_admin, only: [:destroy]

  # GET /beer_clubs or /beer_clubs.json
  def index
    order = params[:order] || 'name'

    @beer_clubs = BeerClub.all
    @beer_clubs = case order
                  when "name" then @beer_clubs.sort_by(&:name)
                  when "founded" then @beer_clubs.sort_by(&:founded)
                  when "city" then @beer_clubs.sort_by(&:city)
                  end
  end

  def join
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1 or /beer_clubs/1.json
  def show
    @membership = Membership.new
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs or /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        Membership.create beer_club_id: @beer_club.id, user_id: current_user.id, confirmed: true

        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully created." }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1 or /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully updated." }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1 or /beer_clubs/1.json
  def destroy
    @beer_club.destroy

    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: "Beer club was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_beer_club.html.erb
<div id="<%= dom_id beer_club %>">
  <h1>
    <%= beer_club.name %>
  </h1>

  <br />

  <p>
    <strong>Founded:</strong>
    <%= beer_club.founded %>
  </p>

  <p>
    <strong>City:</strong>
    <%= beer_club.city %>
  </p>
</div>

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club) do |form| %>
  <% if beer_club.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
        <% beer_club.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :founded, style: "display: block", class: "form-label" %>
    <%= form.number_field :founded, class: "form-control" %>
  </div>

  <div>
    <%= form.label :city, style: "display: block", class: "form-label" %>
    <%= form.text_field :city, class: "form-control" %>
  </div>

  <br>
  <div>
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Show this beer club", @beer_club, class: "btn btn-primary" %>
  <%= link_to "Back to beer clubs", beer_clubs_path, class: "btn btn-primary" %>
</div>

app/views/beer_clubs/index.html.erb
<h1>Beer clubs</h1>

<div id="beerclubs">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col"><%= link_to "Name", beer_clubs_path(order: "name")%></th>
        <th scope="col"><%= link_to "Founded", beer_clubs_path(order: "founded")%></th>
        <th scope="col"><%= link_to "Location", beer_clubs_path(order: "city")%></th>
        <th scope="col" class="text-center">Members</th>

      </tr>
    </thead>
    <tbody>
      <% @beer_clubs.each do |club| %>
        <tr>
          <td><%= link_to club.name, club %></td>
          <td><%= club.founded %></td>
          <td><%= club.city %></td>
          <td class="text-center"><%= club.members.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New beer club", new_beer_club_path, class: "btn btn-primary" if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Back to beer clubs", beer_clubs_path, class: "btn btn-primary" %>
</div>

app/views/beer_clubs/show.html.erb
<%= render @beer_club %>

<div id="members">
  <b>Members</b>
  <ul>
    <% @beer_club.members.each do |member| %>
      <li>
        <%= link_to member.username, user_path(member) %>
      </li>
    <% end %>
  </ul>
</div>

<%if @beer_club.members.include?(current_user) %>
 <%if not @beer_club.applicants.empty? %>
  <div id="applicants">
    <b>Applications</b>
    <ul>
      <% @beer_club.applicants.each do |applicant| %>
        <li>
          <%= form_with(url: accept_membership_path, method: :post) do |form| %>
            <%= link_to applicant.username, user_path(applicant) %>

            <%= form.hidden_field :applicant_id, value: applicant.id %>
            <%= form.submit "accept", class: "btn btn-sm btn-success" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <%end%>
<%end%>

<p>
  <% if current_user %>
    <% if @beer_club.applicants.include?(current_user) %>
      <span class="badge bg-primary">Your application is pending</span>
    <% elsif @beer_club.members.include?(current_user) %>
      <%= form_with(url: membership_path, method: :delete) do |form| %>
        <%= form.hidden_field :beer_club_id, value: @beer_club.id %>
        <%= form.submit "End the membership", class: "btn btn-danger" %>
      <% end %>
    <% else %>
      <%= form_with(model: @membership) do |form| %>
        <%= form.hidden_field :beer_club_id, value: @beer_club.id %>
        <%= form.submit "Join the beer club", class: "btn btn-success" %>
      <% end %>
    <% end %>
  <% end %>
</p>

<div>
  <%= link_to "Back to beer clubs", beer_clubs_path, class:"btn btn-primary" %>
  <%= edit_and_destroy_buttons(@beer_club) if @beer_club.members.include?(current_user)%>
</div>