config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :memberships, only: [:index, :new, :create, :destroy]
  resources :places, only: [:index, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'toggle_activity', on: :member
  end
  resources :memberships do
    post 'accept', on: :member
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'breweries#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  post 'places', to: 'places#search'

  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'

  #get 'kaikki_bisset', to: 'beers#index'
  #get 'ratings', to: 'ratings#index'
  #get 'ratings/new', to:'ratings#new'
  #post 'ratings', to: 'ratings#create'

end

app/models/style.rb
class Style < ApplicationRecord
  extend TopRatings
  include RatingAverage

  has_many :beers
  has_many :ratings, through: :beers

  def to_s
    name
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: %i[show edit update destroy]

  # GET /styles or /styles.json
  def index
    @styles = Style.all
  end

  # GET /styles/1 or /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles or /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to style_url(@style), notice: "Style was successfully created." }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1 or /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to style_url(@style), notice: "Style was successfully updated." }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1 or /styles/1.json
  def destroy
    @style.destroy

    respond_to do |format|
      format.html { redirect_to styles_url, notice: "Style was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_style
    @style = Style.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def style_params
    params.require(:style).permit(:name, :description)
  end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= form_with(model: style) do |form| %>
  <% if style.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
        <% style.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block", class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <br/>
  <div>
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/styles/_style.html.erb
<div id="<%= dom_id style %>">
  <p>
    <strong>Name:</strong>
    <%= style.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= style.description %>
  </p>

  <div id="beers">
    <b>Beers</b>
    <ul>
      <% style.beers.each do |beer| %>
        <li> <%= link_to beer.name, beer %> </li>
      <% end %>
    </ul>
  </div>

</div>

app/views/styles/edit.html.erb
<h1>Editing style</h1>

<%= render "form", style: @style %>

<br>

<div>
  <%= link_to "Show this style", @style, class: "btn btn-primary" %>
  <%= link_to "Back to styles", styles_path, class: "btn btn-primary" %>
</div>

app/views/styles/index.html.erb
<h1>Styles</h1>

<div id="styles">
  <table class="table table-striped">
      <thead>
    <tr>
      <th scope="col">Name</th>
      <th class="text-center" scope="col">Beers</th>
      <th class="text-center" scope="col">Ratings</th>
      <th class="text-center" scope="col">Average</th>
    </tr>
  </thead>
    <tbody>
      <% @styles.each do |style| %>
        <tr>
          <td><%= link_to style.name, style %></td>
          <td class="text-center"><%= style.beers.count %></td>
          <td class="text-center"><%= style.ratings.count %></td>
          <td class="text-center"><%= round(style.average_rating) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New style", new_style_path, class: "btn btn-primary" if current_user %>

app/views/styles/new.html.erb
<h1>New style</h1>

<%= render "form", style: @style %>

<br>

<div>
  <%= link_to "Back to styles", styles_path, class: "btn btn-primary" %>
</div>

app/views/styles/show.html.erb
<%= render @style %>

<div>
  <%= link_to "Back to styles", styles_path, class: "btn btn-primary" %>
  <%= edit_and_destroy_buttons(@style)%>
</div>