config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :memberships, only: [:index, :new, :create, :destroy]
  resources :places, only: [:index, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'toggle_activity', on: :member
  end
  resources :memberships do
    post 'accept', on: :member
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'breweries#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  post 'places', to: 'places#search'

  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'

  #get 'kaikki_bisset', to: 'beers#index'
  #get 'ratings', to: 'ratings#index'
  #get 'ratings/new', to:'ratings#new'
  #post 'ratings', to: 'ratings#create'

end

app/models/brewery.rb
class Brewery < ApplicationRecord
  extend TopRatings
  include RatingAverage

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  validates :name, presence: true, allow_blank: false
  validates :year, numericality: { greater_than_or_equal_to: 1040, less_than_or_equal_to: 2022 }

  scope :active, -> { where active: true }
  scope :retired, -> { where active: [nil, false] }
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: %i[show edit update destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :check_admin, only: [:destroy]
  before_action :brewery_clear_cache, only: [:create, :update, :destroy, :toggle_activity]

  # GET /breweries or /breweries.json
  def index
    return if request.format.html? && fragment_exist?("brewerylist")

    @breweries = Brewery.includes(:beers).all
  end

  def list
  end

  # GET /breweries/1 or /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries or /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to brewery_url(@brewery), notice: "Brewery was successfully created." }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1 or /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to brewery_url(@brewery), notice: "Brewery was successfully updated." }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1 or /breweries/1.json
  def destroy
    @brewery.destroy

    respond_to do |format|
      format.html { redirect_to breweries_url, notice: "Brewery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, !brewery.active

    new_status = brewery.active? ? "active" : "retired"

    redirect_to brewery, notice: "brewery activity status changed to #{new_status}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_brewery.html.erb
<% cache @brewery do %>
  <div id="<%= dom_id brewery %>">
    <h2>
      <%= brewery.name %>
      <% if not brewery.active  %>
        <span class="badge bg-secondary">retired</span>
      <% end %>
    </h2>

    <i>
      Established at <%= brewery.year %>
    </i>

    <p>
      Beers count: <%= brewery.beers.count %>
    </p>

    <div id="beers">
      <table class="table">
          <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Style</th>

          <th scope="col" class="text-center">Ratings received</th>
          <th scope="col" class="text-center">Average rating</th>
        </tr>
      </thead>
        <tbody>
          <% @brewery.beers.each do |beer| %>
            <tr>
              <td><%= link_to beer.name, beer %></td>
              <td><%= link_to beer.style %></td>
              <td class="text-center"><%= beer.ratings.count %></td>
              <td class="text-center"><%= round(beer.average_rating) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <p>
      <% if brewery.ratings.empty? %>
        This brewery has no rated beers
      <% else %>
        Brewery has 
        <b><%= brewery.beers.count %> <%= 'beer'.pluralize(brewery.beers.count) %></b>
        with total of
        <b><%= brewery.ratings.count %> <%= 'rating'.pluralize(brewery.ratings.count) %></b>
        which average rating is
        <b><%= round(brewery.average_rating) %></b>
      <% end %>
    </p>

  </div>
<% end %>

app/views/breweries/_form.html.erb
<%= form_with(model: brewery) do |form| %>
  <% if brewery.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
        <% brewery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :year, style: "display: block", class: "form-label" %>
    <%= form.number_field :year, class: "form-control" %>
  </div>

  <div>
    <%= form.label :active, style: "display: block", class: "form-label" %>
    <%= form.check_box :active, class: "form-check-input" %>
  </div>

  <br />
  <div>
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Show this brewery", @brewery, class: "btn btn-primary" %>
  <%= link_to "Back to breweries", breweries_path, class: "btn btn-primary" %>
</div>

app/views/breweries/index.html.erb
<h1>Breweries</h1>

<% cache "brewerylist", skip_digest: true, expires_in: 15.minutes do %>

  <h3>Number of breweries: <%= @breweries.count %></h3>

  <div id="breweries">
    <table class="table">
        <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Founded</th>
        <th scope="col">Beers</th>
        <th scope="col" class="nowrap text-center">Average rating</th>
        <th style="width: 5%"></th>
      </tr>
    </thead>
      <tbody>
        <% @breweries.each do |brewery| %>
          <tr>
            <td><%= link_to brewery.name, brewery %></td>
            <td><%= brewery.year %></td>
            <td><%= brewery.beers.size %></td>
            <td class="text-center"><%= round(brewery.average_rating) %></td>
            <% if brewery.active %>
              <td></td>
            <% else %>
              <td><span class="badge bg-secondary">retired</span></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<%= link_to "New brewery", new_brewery_path, class: "btn btn-primary" if current_user %>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<p id="reverse">reverse!</p>

<div id="breweries">
  <table id="brewerytable" class="table table-hover">
    <thead>
      <tr>
        <th> <span id="name">Name</span> </th>
        <th> <span id="year">Year</span> </th>
        <th> <span id="beerquantity">Amount of beers</span> </th>
        <th> <span id="active">Active</span> </th>
      </tr>
    <thead>
    <tbody>
      <div id="beerlist"></div>
    </tbody>
  </table>
</div>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Back to breweries", breweries_path, class: "btn btn-primary" %>
</div>

app/views/breweries/panimot.html.erb
panimoita <%= @breweries.count %>

app/views/breweries/show.html.erb
<%= render @brewery %>


<%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), data: {turbo_method: "post"}, class: "btn btn-primary" if current_user %>

<div>
  <br>
  <%= link_to "Back to breweries", breweries_path, class: "btn btn-primary" %>
  <%= edit_and_destroy_buttons(@brewery)%>
</div>